module.exports =
	Application:
		defaultPort: 3000
		defaultLang: "en-us"
		defaultCharset: "UTF-8"
		favicon: "favicon.ico"
		timeFormat: "LLL"
		publicPath: "/public"
		viewPath: "/views"
		routePath: "/routes"
		subjectPath: "/subjects"
		dataPath: "/data"
		viewEngine: "jade"
		techContact: "Technical Administrator"
		techContactEmail: "dev@example.com"
		Routes:
			adminRoute: "/admin"
	Experiment:
		experimentName: "A JDM Experiment"
		primaryInvestigator: "Primary Investigator"
		primaryInvestigatorEmail: "pi@example.com"
		primaryInvestigatorLogin: "primaryInvestigator"
		primaryInvestigatorPassword: "judgmentAndDecisionMaking"
	Errors:
		errorNoSubjectFileSpecified: "No subject file specified."
		errorDefault: "An error has occurred. Please notify the system administrator"
		errorInvalidSubject: "Participant not found"
		errorNoGridFile: "Grid file not present."
		errorNoSlidersFile: "Sliders file not present."
		errorNoSurveyFile: "Survey file not present."
		errorInvalidExperiment: "Invalid experiment."
		errorInvalidPhase: "Invalid experiment step."
		errorInvalidRankMode: "Not a valid ranking mode for choice grid."
		errorInvalidCredentials: "Invalid request."
		errorMalformedCommand: "Malformed command received.  Check syntax."
		errorBadConfiguration: "Bad configuration file. Please notify the system administrator"
